import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1>in place</h1>
          <text className={styles.statement}>i accept my work as imperfect.</text>
          <text className={styles.statement}>i seek to let my process breathe.</text>
          <text className={styles.statement}>i curate my perspective of the world into ideas and form.</text>
          <text className={styles.statement}>i share my work to let my experiences be enjoyed by others.</text>
          <text className={styles.statement}>i cultivate a garden of joy.</text>
        </div>
      </main>
    </>
  );
}
